language: ruby
sudo: false
rvm:
  - 2.5.0

before_install:
  - gem update --system

services:
  - postgresql
  - mysql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true
  - mysql -u root -e 'create database octobox_test;' || true

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test && bundle exec codeclimate-test-reporter

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  matrix:
    - DATABASE=mysql2
    - DATABASE=postgresql

notifications:
  email: false
