language: ruby
sudo: false
rvm:
  - 2.4.0

services:
  - postgresql

before_script:
  - psql -c 'create database "octobox_test";' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test && bundle exec codeclimate-test-reporter
  - bundle exec teaspoon

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

notifications:
  email: false
