language: ruby
sudo: false
rvm:
  - 2.5.1

before_install:
  - gem update --system
  - gem install bundler

addons:
  firefox: latest
  postgresql: "9.6"

services:
  - postgresql
  - mysql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true
  - mysql -u root -e 'create database octobox_test;' || true

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  MOZ_HEADLESS=1
  matrix:
    - DATABASE=mysql2
    - DATABASE=postgresql

notifications:
  email: false
