---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %> # From lib/database_config.rb
:queues:
  - [user, 4]
  - [comments, 3]
  - [sync_notifications, 2]
  - [marketplace, 2]
  - [sync_subjects, 1]
  - [sync_repos, 1]
